package com.example.assignment1;

public class attack {

    private String name;
    private String description;
    private int imageID;



    public static final attack[] attackers = {

            new attack("Leo Messi", "Lionel Andrés Messi (born 24 June 1987), also known as Leo Messi, is an Argentine professional footballer who plays as a forward for Ligue 1 club Paris Saint-Germain and captains the Argentina national team. Often considered the best player in the world and widely regarded as one of the greatest players of all time, Messi has won a record six Ballon d'Or awards, a record six European Golden Shoes, and in 2020 was named to the Ballon d'Or Dream Team. Until leaving the club in 2021, he had spent his entire professional career with Barcelona, where he won a club-record 35 trophies, including ten La Liga titles, seven Copa del Rey titles and four UEFA Champions Leagues. A prolific goalscorer and creative playmaker, Messi holds the records for most goals in La Liga (474), a La Liga and European league season (50), most hat-tricks in La Liga (36) and the UEFA Champions League (8), and most assists in La Liga (192), a La Liga season (21) and the Copa América (17). He also holds the record for most international goals by a South American male (80). Messi has scored over 750 senior career goals for club and country, and has the most goals by a player for a single club.\n" +
                    "\n" +
                    "Born and raised in central Argentina, Messi relocated to Spain to join Barcelona at age 13, for whom he made his competitive debut aged 17 in October 2004. He established himself as an integral player for the club within the next three years, and in his first uninterrupted season in 2008–09 he helped Barcelona achieve the first treble in Spanish football; that year, aged 22, Messi won his first Ballon d'Or. Three successful seasons followed, with Messi winning four consecutive Ballons d'Or, making him the first player to win the award four times and in a row. During the 2011–12 season, he set the La Liga and European records for most goals scored in a single season, while establishing himself as Barcelona's all-time top scorer. The following two seasons, Messi finished second for the Ballon d'Or behind Cristiano Ronaldo (his perceived career rival), before regaining his best form during the 2014–15 campaign, becoming the all-time top scorer in La Liga and leading Barcelona to a historic second treble, after which he was awarded a fifth Ballon d'Or in 2015. Messi assumed captaincy of Barcelona in 2018, and in 2019 he won a record sixth Ballon d'Or.\n" +
                    "\n" +
                    "An Argentine international, Messi is both his country's highest appearance-maker and their all-time leading goalscorer. At youth level, he won the 2005 FIFA World Youth Championship, finishing the tournament with both the Golden Ball and Golden Shoe, and an Olympic gold medal at the 2008 Summer Olympics. His style of play as a diminutive, left-footed dribbler drew comparisons with his compatriot Diego Maradona, who described Messi as his successor. After his senior debut in August 2005, Messi became the youngest Argentine to play and score in a FIFA World Cup in 2006, and reached the final of the 2007 Copa América, where he was named young player of the tournament. As the squad's captain from August 2011, he led Argentina to three consecutive finals: the 2014 FIFA World Cup, for which he won the Golden Ball, and the 2015 and 2016 Copa América, winning the Golden Ball in the 2015 edition. After announcing his international retirement in 2016, he reversed his decision and led his country to qualification for the 2018 FIFA World Cup, a third-place finish at the 2019 Copa América, and won the 2021 Copa América, while winning the Golden Ball and Golden Boot award for the latter.\n" +
                    "\n" +
                    "Messi has endorsed sportswear company Adidas since 2006. According to France Football, he was the world's highest-paid footballer for five years out of six between 2009 and 2014, and was ranked the world's highest-paid athlete by Forbes in 2019. Messi was among Time's 100 most influential people in the world in 2011 and 2012. In February 2020, he was awarded the Laureus World Sportsman of the Year, thus becoming the first footballer and the first team sport athlete to win the award. Later that year, Messi became the second footballer (and second team-sport athlete) to surpass $1 billion in career earnings.", R.drawable.messi),


            new attack("Samual Etto", "Samuel Eto'o Fils (born 10 March 1981) is a Cameroonian retired professional footballer who played as a striker. In his prime, Eto'o was regarded by pundits as one of the best strikers in the world, and he is regarded as one of the greatest African players of all time, winning the African Player of the Year a record four times: in 2003, 2004, 2005, and 2010.\n" +
                    "\n" +
                    "A precocious talent, Eto'o moved to Real Madrid as a 16 year old. Due to competition in his position with more experienced players, he had several loan spells, before signing for Mallorca in 2000 where he scored 70 goals. His impressive form saw him join Barcelona in 2004 where he scored 130 goals in five seasons and also became the record holder for the most appearances by an African player in La Liga. Winning La Liga three times, he was a key member of the Barcelona attack, alongside Ronaldinho, that won the 2006 UEFA Champions League Final, with Eto'o scoring in the final, and was part of a front three of Lionel Messi and Thierry Henry that won the 2009 UEFA Champions League Final, with Eto'o again scoring in the final. He is the second player in history to score in two UEFA Champions League finals. At Barcelona, Eto'o came in third for the FIFA World Player of the Year in 2005 and was twice named in the FIFA FIFPro World XI, in 2005 and 2006.\n" +
                    "\n" +
                    "He signed with Inter Milan for the 2009-10 season, where he became the first player to win two European continental trebles following his back-to-back achievements with Barcelona and Inter. He is the fourth player in Champions League history, after Marcel Desailly, Paulo Sousa, and Gerard Piqué, to have won the trophy two years in a row with different teams. After brief spells with Anzhi Makhachkala, Chelsea, Everton, and Sampdoria, Eto'o found prolific form again in the Süper Lig with Antalyaspor having scored 44 goals in 76 league games. In 2015, he received the Golden Foot Award.\n" +
                    "\n" +
                    "As a member of the Cameroon national team, Eto'o was a part of the squad that won the Gold Medal at the 2000 Olympics. He also won the Africa Cup of Nations in 2000 and 2002. Eto'o has participated in four World Cups and six Africa Cup of Nations. He is the all-time leading scorer in the history of the Africa Cup of Nations, with 18 goals, and is Cameroon's all-time leading scorer and third most capped player, with 56 goals in 118 caps. Eto'o announced his retirement from international football in August 2014.\n" +
                    "\n" +
                    "Eto'o departed Mallorca as the club's all-time leading domestic league scorer (54 goals) when he signed for Barcelona in the summer of 2004 for a transfer fee of €24 million, after lengthy, three-way negotiations with Mallorca and Madrid. Initially, Real Madrid President Florentino Pérez wanted to buy back the full transfer rights and loan him out again, but eventually the Barcelona deal proved lucrative enough to warrant a sale. Additionally, the team already had its full quota of three non-EU players.\n" +
                    "\n" +
                    "Eto'o made his Barcelona debut in the season opener at Racing de Santander on 29 August 2004. After Barcelona won the 2004–05 La Liga title, the team organized a festive party in the Camp Nou, during which Eto'o harangued the fans chanting, \"Madrid, cabrón, saluda al campeón\" (English for, \"Madrid, bastards, salute the champions\"). The Royal Spanish Football Federation fined Eto'o €12,000 for his comments, for which he later apologized. He expressed regret and asked for forgiveness from Real Madrid, his first professional team. The head of the Real Madrid fan club federation remained unimpressed, however, stating, \"This character is a fantastic player, but he leaves a lot to be desired as a person.\" He signed an improved contract with Barcelona in June 2005.\n" +
                    "\n" +
                    "After missing out on the previous year's Pichichi trophy, which is given to the top scorer in La Liga, Eto'o edged out Valencia striker David Villa for the award during the final matchday on 20 May 2006 when he scored his 26th goal of the season against Athletic Bilbao. Eto'o was very gracious to teammates after the game, saying, \"It has been a team effort although only one person gets the award. We've worked hard all season and have got our just rewards.\"\n" +
                    "\n" +
                    "Eto'o also contributed six goals during Barcelona's run to the 2005–06 Champions League title. In the final, Arsenal goalkeeper Jens Lehmann was sent off early on for bringing down Eto'o just outside the penalty area, but the Catalans struggled to capitalize on their one-man advantage until Eto'o scored the game-tying goal in the second half. Barcelona went on to win the match 2–1, and Eto'o was awarded with the UEFA Best Forward of the Year award for his accomplishments in the European campaign.\n" +
                    "\n" +
                    "Eto'o also won an historic third consecutive African Player of the Year award that season. He said in his acceptance speech, \"Above all, I dedicate this to all the children of Africa.\" He was also selected to his second straight FIFPro World XI and finished third in the running for the FIFA World Player of the Year, making him only the second African footballer ever, after the Liberian star George Weah, to be voted into the top three.\n" +
                    "\n" +
                    "The season started badly for Eto'o, as he ruptured the meniscus in his right knee during Barcelona's Champions League group stage match against Werder Bremen on 27 September 2006. Barcelona team physician Ricard Pruna originally estimated that the injury would keep him out of action for two to three months.[26] After the operation, Eto'o's recovery time was extended to five months, but he resumed training with Barcelona in early January 2007.", R.drawable.etto),


            new attack("Luis Suarez", "Luis Alberto Suárez Díaz (born 24 January 1987) is a Uruguayan professional footballer who plays as a striker for Spanish club Atlético Madrid and the Uruguay national team. Regarded as one of the best players of his generation, and one of the greatest strikers of all time, Suárez has won nineteen major trophies in his career, including seven league titles and a UEFA Champions League at club level, as well as the 2011 Copa América with Uruguay. Suárez has won two European Golden Shoes, an Eredivisie Golden Boot, a Premier League Golden Boot, and the Pichichi Trophy. He has scored over 500 career goals for club and country.\n" +
                    "\n" +
                    "Nicknamed El Pistolero ('The Gunman'), Suárez began his senior club career at Nacional in 2005. At age 19, he signed for Groningen, before transferring to Ajax in 2007. There, he won an Eredivisie title and KNVB Cup. In 2011, Suárez signed for Premier League club Liverpool, and won the League Cup in his first full season. In 2014, he equalled the goalscoring record for a 38-game Premier League season and won his first European Golden Shoe. That summer, Suárez moved to Barcelona in a transfer worth €82.3 million (£64.98 million), making him one of the most expensive players in football history.\n" +
                    "\n" +
                    "In his first season, he won a continental treble of La Liga, the Copa del Rey and the UEFA Champions League with Barcelona. In his second season, Suárez won the Pichichi Trophy and his second European Golden Shoe, becoming the first player since 2009 to win both awards other than Lionel Messi or Cristiano Ronaldo. He also led La Liga in assists, becoming the first player to do so in both goals and assists in league history. With Barcelona, he won ten additional trophies, including three La Liga titles and three Copas del Rey. He signed for Atlético Madrid in 2020, winning his fifth La Liga title on his debut season.\n" +
                    "\n" +
                    "At international level, Suárez is Uruguay's all-time leading goalscorer, and has represented his nation at three editions of the FIFA World Cup and four editions of the Copa América, as well as the 2012 Summer Olympics and the 2013 FIFA Confederations Cup.\n" +
                    "\n" +
                    "Suárez has been a source of controversy throughout his career. As well as his goal-line handball against Ghana at the 2010 FIFA World Cup, he has also bitten opponents on three occasions. Suárez has also been accused of and admitted to diving, and in 2011, the FA found him guilty of racially abusing Patrice Evra.\n" +
                    "\n" +
                    "On 11 July 2014, Suárez agreed with Barcelona on a five-year contract for an undisclosed transfer fee. However, according to a leaked document by Football Leaks, the fee was £64.98 million (€82.3 million), making him one of the most expensive players in world football history. Barça confirmed Suárez would wear the number 9 shirt for the 2014–15 season.\n" +
                    "\n" +
                    "Suárez missed the first part of the season after being found guilty of biting Italian player Giorgio Chiellini at the 2014 FIFA World Cup. As part of the suspension, he was banned from all \"football-related activities\", including training for Barcelona, for four months (until 26 October). He was also banned from entering any stadium, even as a spectator, during the same period.\n" +
                    "\n" +
                    "On 24 July, Suárez and his lawyers filed an appeal with the Court of Arbitration for Sport (CAS) and requested the sanctions be reduced or the suspension to be lifted.[158] The parties were heard at a hearing which took place at the CAS offices in Lausanne, Switzerland, on 8 August.[159] Six days later, the CAS confirmed the ban imposed by FIFA against Suárez, who remained suspended from football for four months, as well as a nine-match ban in internationals, the first of which was served in the Uruguay's round of 16 match against Colombia in the 2014 World Cup. However, the CAS removed the player's \"football-related activities\" ban and was allowed to train with Barcelona. As a result of this ban, Suárez was banned from participating in the 2015 Copa América.\n" +
                    "\n" +
                    "The CAS permitted Suárez to play in friendly matches, and he made his Barcelona debut on 18 August against Club León of Mexico at the Camp Nou, replacing Rafinha for the final 14 minutes of an eventual 6–0 win in the Gamper Trophy. Fellow forwards Lionel Messi and Neymar had already been substituted off by the time Suárez took to the pitch.", R.drawable.suaez)
    };




    private attack(String name, String description, int imageID){
        this.name = name;
        this.description = description;
        this.imageID = imageID;
    }
    public String getName(){return name;}
    public String getDescription(){return description;}
    public int getImageID(){return imageID;}

    @Override
    public String toString(){return name;}
}
